# PL_SAC_Beta algorithm-specific parameters
beta_concentration_offset: 1.0
beta_concentration_eps: 1.0e-6

# Use SB3-style ent_coef: can be a float (fixed) or a string 'auto' / 'auto_<init_value>'
ent_coef: 'auto'
target_entropy: auto
target_update_interval: 1
policy_freq: 1
