# SAC + Success-Buffer Prioritized Experience Replay.
ent_coef: 'auto'
target_entropy: auto
target_update_interval: 1
policy_freq: 1
use_stacked_depth: false

sb_per_alpha: 0.6
sb_per_beta0: 0.4
sb_per_beta1: 1.0
sb_per_eps: 0.000001
sb_per_success_capacity_ratio: 0.3
sb_per_success_sample_ratio: 0.30
sb_per_mu_low: 0.30
sb_per_mu_mid: 0.40
sb_per_mu_high: 0.45
sb_per_mu_step1: 0.25
sb_per_mu_step2: 0.70
